import { getAllAnimes } from '@/modules/anime/application/getAllAnimes'
import { apiAnimeRepository } from '@/modules/anime/infrastructure/animeRepository'
import { ViewAnimes } from '@/sections/Anime/views/AnimePage.container'
import Head from 'next/head'

export default function Home() {
  const animeRepository = apiAnimeRepository();
  return (
    <>
      <Head>
        <title>Hexagonal Architecture Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ViewAnimes getAllAnimes={getAllAnimes} repository={animeRepository}/>
      </main>
    </>
  )
}
